# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ordinary_price', models.IntegerField()),
                ('pricing_unit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_count', models.IntegerField(default=0)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Bucket')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Good')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_good_count', models.IntegerField()),
                ('special_price', models.IntegerField()),
                ('good_count', models.IntegerField()),
                ('condition_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_good', to='market.Good')),
                ('target_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_good', to='market.Good')),
            ],
        ),
    ]
